### ISSUE TITLE
快速重复多次开始停止就崩溃了

### ISSUE THREAD

**Issue by h1091129209** [GavinCT/AndroidMP3Recorder#26]
这个问题很严重

**Comment by GavinCT** [comment]
放崩溃日志啊

**Comment by LeooooL** [comment]
这种情况的解决办法是start()不要绑定onClick事件，使用手势识别的方式替代。OnGestureListener.onShowPress()

**Comment by GavinCT** [comment]
。。。能给个崩溃日志么 各位

**Comment by ArthurHan** [comment]
小米4，跑sample，点击开始不弹出"开启录音权限，是否允许"的提示，接着崩溃，在设置手动设置该应用允许，可以录音，log如下:
10-08 17:03:17.649 294-9752/? E/AudioFlinger: openRecord() permission denied: recording not allowed
10-08 17:03:17.649 2633-2633/com.czt.mp3recorder.sample E/AudioRecord: AudioFlinger could not create record track, status: -1
10-08 17:03:17.653 2633-2633/com.czt.mp3recorder.sample E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -1.
10-08 17:03:17.654 2633-2633/com.czt.mp3recorder.sample E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
10-08 17:03:17.684 2633-2633/com.czt.mp3recorder.sample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: com.czt.mp3recorder.sample, PID: 2633
                                                                          java.lang.IllegalStateException: startRecording() called on an uninitialized AudioRecord.
                                                                              at android.media.AudioRecord.startRecording(AudioRecord.java:895)
                                                                              at com.czt.mp3recorder.MP3Recorder.start(MP3Recorder.java:70)
                                                                              at com.czt.mp3recorder.sample.MainActivity$1.onClick(MainActivity.java:29)
                                                                              at android.view.View.performClick(View.java:5207)
                                                                              at android.view.View$PerformClick.run(View.java:21177)
                                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:148)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5438)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by GavinCT** [comment]
@ArthurHan Sample没有针对6.0申请权限，一直没时间改。 google一下加权限的教程即可。 
mp3库里加权限不方便，因为android权限和activity绑死了，所以最好由使用者自己申请
