### ISSUE TITLE
 java.lang.UnsatisfiedLinkErro

### ISSUE THREAD

**Issue by anhdiepmmk** [GavinCT/AndroidMP3Recorder#5]
I using library for my project but receive error in device xiaomi "Mi phone 4i" plz help me 
java.lang.UnsatisfiedLinkError: No implementation found for void com.czt.mp3recorder.util.LameUtil.init(int, int, int, int, int) (tried Java_com_czt_mp3recorder_util_LameUtil_init and Java_com_czt_mp3recorder_util_LameUtil_init__IIIII)
            at com.czt.mp3recorder.util.LameUtil.init(Native Method)
            at com.czt.mp3recorder.MP3Recorder.initAudioRecorder(MP3Recorder.java:155)
            at com.czt.mp3recorder.MP3Recorder.start(MP3Recorder.java:66)

**Comment by GavinCT** [comment]
https://github.com/GavinCT/AndroidMP3Recorder#5-常见问题声明
