### ISSUE TITLE
Crash on marshmallow

### ISSUE THREAD

**Issue by vinod-morya** [GavinCT/AndroidMP3Recorder#8]
The crash occurs as soon as i call mRecorder.start(), i cross verified all the variables before posting this issue.
The code works fine on below versions of android.

 E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.wamedia.waforever, PID: 18933
                                                   java.lang.IllegalStateException: startRecording() called on an uninitialized AudioRecord.
                                                       at android.media.AudioRecord.startRecording(AudioRecord.java:885)
                                                       at com.czt.mp3recorder.MP3Recorder.start(MP3Recorder.java:67)
                                                       at com.wamedia.waforever.ui.fragments.WaFutureCreateFragment.onPositiveClick(HelloFragment.java:532)
                                                       at com.wamedia.waforever.ui.widgets.ConfirmDialogFragment$2.onClick(DialogFragment.java:106)
                                                       at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:163)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
 I/Process: Sending signal. PID: 18933 SIG: 9

**Comment by GavinCT** [comment]
sorry i used genymotion marshmallow version, it works normally

**Comment by GavinCT** [comment]
please try my sample. or try new version

compile 'com.czt.mp3recorder:library:1.0.1'

2015-11-25 5:05 GMT+08:00 vinod-morya <notifications@github.com>:
